### ISSUE TITLE
This script will be terminated prematurely because the following error has occurred:   Cannot process file: mandatory "Where" field is missing. (Error number: -2700)

### ISSUE THREAD

**Issue by Webstere12357** [lifepillar/CSVKeychain#2]
I'm trying to import the .csv file to the keychain file, but I get this error, and I don't
 know what is going wrong.
<img width="569" alt="error" src="https://user-images.githubusercontent.com/20637896/34638999-4182d634-f2a5-11e7-89c6-02469c98bc71.png">

**Comment by lifepillar** [comment]
Where does your CSV come from? You cannot (directly) import any CSV file: you can only (directly) import files that have been exported by CSVKeychain itself. If you are building your CSV file in some other way, then it must have the following header:

```
"Where","Account","Password","Label","Comment","Created","Modified","Kind","Type","Domain","AuthType","Class","Creator"
```

and all fields must be double-quoted. Only the `Where` and `Account` values are mandatory (cannot be empty). This is an example of a valid CSV file:

```
"Where","Account","Password","Label","Comment","Created","Modified","Kind","Type","Domain","AuthType","Class","Creator"
"MyApp","myusername","verystrong12345","www.foo.com","","20171126170739","20171210145348","application password","","","","genp","sckj"
"smb://my.network.mount","XYZ","password123","","","","","Network password","","","","inet",""
"https://some.site.org","myusername","mypassword","","","","","internet password","","","","inet",""
"Minimal record","MyAccount","","","","","","","","","","",""
```

Also, make sure to use the current master, because I have just fixed a typo in the code, which caused an error when an Internet password does not have an associated Label.

Does it help?

**Comment by Webstere12357** [comment]
Thank you, I've been trying to import my chrome passwords into keychain and its been a long journey, but I'm almost there thanks to you. I just have one more problem when I'm importing it's giving me an error because the script is entering a password to allow the transfer and it's not my account password. I don't know where that line is or if I could change it so it puts in my password and I don't have to click allow and type my password for all of my passwords.

**Comment by lifepillar** [comment]
Closing for lack of feedback (I assume you fixed your issue). Feel free to reopen if necessary.
